// devices.js -- Literary devices: match cards into rows (name > definition > example).
//
// The same pool as the teacher's quiz: data/devices.json is generated by the toolkit's
// editions/devices/quiz.py --app-json, so practice and quiz cannot drift apart.
//
// A PAGE OF ITS OWN, deliberately apart from app.js: it touches no scansion state and STORES
// NOTHING -- no localStorage at all -- so the privacy notice on the scansion page stays true
// and no student's progress can be disturbed by it.
//
// Placing is TAP-TAP (a card, then a space), because it works the same with a finger, a mouse
// and a keyboard (every card and space is a button). A card goes only into its own column.
"use strict";

(() => {
  const $ = (id) => document.getElementById(id);
  const board = $("dv-board"), tray = $("dv-tray"), feedback = $("dv-feedback");
  const COLS = [["name", "Name"], ["definition", "Definition"], ["example", "Example"]];
  let POOL = [], rows = [], cards = [], selected = null, checked = false;
  // The cards stay in reach (a sidebar, or a drawer on a narrow screen), so nothing scrolls back
  // to them. What can still be off-screen is the SPACE a picked card goes to: bring the first
  // one into view, unless it is already there.
  const glide = (el) => {
    if (!el) return;
    const r = el.getBoundingClientRect();
    const bottom = window.innerHeight - ($("dv-side").classList.contains("dv-drawer")
      ? $("dv-side").offsetHeight : 0);
    if (r.top < 0 || r.bottom > bottom) el.scrollIntoView({ behavior: "smooth", block: "center" });
  };

  const shuffle = (a) => {
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  };

  // ---- a card's face ---------------------------------------------------------------------------
  function face(card) {
    const el = document.createElement("span");
    el.className = "dv-face";
    if (card.kind === "name") {
      el.textContent = card.text;
    } else if (card.kind === "definition") {
      el.textContent = card.text;
    } else {
      const ex = card.example;
      const cite = document.createElement("span");
      cite.className = "dv-cite";
      cite.textContent = ex.cite;
      el.appendChild(cite);
      for (const line of ex.latin) {
        const l = document.createElement("span");
        l.className = "dv-latin";
        l.lang = "la";
        for (const [t, bold] of line) {
          const r = document.createElement(bold ? "b" : "span");
          r.textContent = t;
          l.appendChild(r);
        }
        el.appendChild(l);
      }
      const en = document.createElement("span");
      en.className = "dv-english";
      en.textContent = ex.english;
      el.appendChild(en);
    }
    return el;
  }

  function cardButton(card) {
    const b = document.createElement("button");
    b.type = "button";
    b.className = `dv-card dv-${card.kind}`;
    if (card === selected) b.classList.add("selected");
    if (checked && card.slot) b.classList.add(card.slot.row.key === card.key ? "ok" : "bad");
    b.setAttribute("aria-label", `${card.kind} card`);
    const tag = document.createElement("span");
    tag.className = "dv-tag";
    tag.textContent = card.kind;
    b.appendChild(tag);
    b.appendChild(face(card));
    b.addEventListener("click", () => tapCard(card));
    return b;
  }

  // ---- drawing ---------------------------------------------------------------------------------
  function draw() {
    document.body.classList.toggle("dv-no-english", !$("dv-english").checked);
    board.replaceChildren();
    const head = document.createElement("div");
    head.className = "dv-row dv-head";
    head.setAttribute("role", "row");
    for (const [, label] of COLS) {
      const h = document.createElement("div");
      h.className = "dv-cell";
      h.setAttribute("role", "columnheader");
      h.textContent = label;
      head.appendChild(h);
    }
    board.appendChild(head);

    for (const row of rows) {
      const r = document.createElement("div");
      r.className = "dv-row";
      r.setAttribute("role", "row");
      for (const [kind, label] of COLS) {
        const c = document.createElement("div");
        c.className = `dv-cell dv-col-${kind}`;
        c.setAttribute("role", "cell");
        const lab = document.createElement("span");
        lab.className = "dv-slot-label";
        lab.textContent = label;
        c.appendChild(lab);
        const placed = row.slots[kind];
        if (row.fixed && kind === "name") {
          const fixed = document.createElement("div");
          fixed.className = "dv-fixed";
          fixed.textContent = row.name;
          c.appendChild(fixed);
        } else if (placed) {
          c.appendChild(cardButton(placed));
        } else {
          const s = document.createElement("button");
          s.type = "button";
          s.className = "dv-slot";
          if (selected && selected.kind === kind) s.classList.add("ready");
          s.setAttribute("aria-label", `empty ${label.toLowerCase()} space`);
          s.textContent = selected && selected.kind === kind ? "place here" : "";
          s.addEventListener("click", () => tapSlot(row, kind));
          c.appendChild(s);
        }
        r.appendChild(c);
      }
      board.appendChild(r);
    }

    tray.replaceChildren();
    const loose = cards.filter((c) => !c.slot);
    for (const c of loose) tray.appendChild(cardButton(c));
    $("dv-count").textContent = loose.length ? `(${loose.length} to place)` : "(all placed)";
    tray.classList.toggle("dv-empty", loose.length === 0);
    if (!loose.length) {
      const done = document.createElement("p");
      done.className = "dv-done";
      done.textContent = checked ? "" : "Every card is placed. Check your rows!";
      tray.appendChild(done);
    }
  }

  // ---- moves -----------------------------------------------------------------------------------
  function tapCard(card) {
    if (card.slot) {                               // a placed card goes back to the tray
      card.slot.row.slots[card.kind] = null;
      card.slot = null;
      selected = null;
      checked = false;
      feedback.textContent = "";
    } else {
      selected = selected === card ? null : card;
    }
    draw();
    if (selected) glide(board.querySelector(".dv-slot.ready"));
  }

  function tapSlot(row, kind) {
    if (!selected) {
      feedback.textContent = "Tap a card first, then the space where it belongs.";
      return;
    }
    if (selected.kind !== kind) {
      feedback.textContent = `That is ${selected.kind === "example" ? "an" : "a"} ${selected.kind} card: it goes in the ${selected.kind} column.`;
      return;
    }
    selected.slot = { row };
    row.slots[kind] = selected;
    selected = null;
    checked = false;
    feedback.textContent = "";
    draw();
  }

  function check() {
    const placed = cards.filter((c) => c.slot);
    if (!placed.length) {
      feedback.textContent = "Place some cards first.";
      return;
    }
    checked = true;
    selected = null;
    const right = placed.filter((c) => c.slot.row.key === c.key).length;
    const total = cards.length;
    draw();
    feedback.replaceChildren();
    const p = document.createElement("div");
    if (right === total) {
      p.innerHTML = `<b>All ${rows.length} rows right!</b>`;
      const n = document.createElement("div");
      n.className = "note";
      n.textContent = "Try New round, or tick Names are cards too for a harder one.";
      feedback.append(p, n);
    } else {
      p.textContent = `${right} of ${total} cards in the right row.` +
        (placed.length < total ? ` ${total - placed.length} still to place.` : "");
      const n = document.createElement("div");
      n.className = "note";
      n.textContent = "Red cards are in the wrong row: tap one to take it back.";
      feedback.append(p, n);
    }
  }

  function reveal() {
    for (const c of cards) {
      if (c.slot) c.slot.row.slots[c.kind] = null;
      c.slot = null;
    }
    for (const c of cards) {
      const row = rows.find((r) => r.key === c.key);
      row.slots[c.kind] = c;
      c.slot = { row };
    }
    selected = null;
    checked = true;
    draw();
    feedback.textContent = "Here is every row. New round when you are ready.";
  }

  function newRound() {
    const n = Number($("dv-rows").value);
    const namesToo = $("dv-names").checked;
    const picked = shuffle(POOL.slice()).slice(0, n);
    rows = picked.map((d) => ({
      key: d.key, name: d.name, fixed: !namesToo,
      slots: { name: null, definition: null, example: null },
    }));
    cards = [];
    for (const d of picked) {
      const ex = d.examples[Math.floor(Math.random() * d.examples.length)];
      cards.push({ key: d.key, kind: "definition", text: d.definition });
      cards.push({ key: d.key, kind: "example", example: ex });
      if (namesToo) cards.push({ key: d.key, kind: "name", text: d.name });
    }
    shuffle(cards);
    shuffle(rows);
    selected = null;
    checked = false;
    feedback.textContent = "";
    draw();
  }

  // ---- start -----------------------------------------------------------------------------------
  // the fold: kept only while the page is open (this page stores nothing)
  const NARROW = window.matchMedia("(max-width: 60rem)");
  const side = $("dv-side"), toggle = $("dv-side-toggle");
  const placeSide = () => side.classList.toggle("dv-drawer", NARROW.matches);
  placeSide();
  NARROW.addEventListener("change", placeSide);
  toggle.addEventListener("click", () => {
    const open = side.classList.toggle("dv-folded") === false;
    toggle.setAttribute("aria-expanded", String(open));
  });
  $("dv-check").addEventListener("click", check);
  $("dv-reveal").addEventListener("click", reveal);
  $("dv-new").addEventListener("click", newRound);
  $("dv-rows").addEventListener("change", newRound);
  $("dv-names").addEventListener("change", newRound);
  $("dv-english").addEventListener("change", draw);

  fetch("data/devices.json", { cache: "no-cache" })
    .then((r) => r.json())
    .then((d) => { POOL = d.devices; newRound(); })
    .catch(() => { feedback.textContent = "The devices could not be loaded. Try reloading the page."; });
})();
